<?php 


define('HTTP_CODE_OK', 200);
define('HTTP_CODE_CREATED', 201);
define('HTTP_CODE_ACCEPTED', 202);
define('HTTP_CODE_NO_CONTENT', 204);
define('HTTP_CODE_BAD_REQUEST', 400);
define('HTTP_CODE_UNAUTHORIZED', 401);
define('HTTP_CODE_FORBIDDEN', 403);
define('HTTP_CODE_NOT_FOUND', 404);
define('HTTP_CODE_METHOD_NOT_ALLOWED', 405);
define('HTTP_CODE_NOT_ACCEPTABLE', 406);
define('HTTP_CODE_INTERNAL_SERVER_ERROR', 500);
